application: vast-mapper-586
version: 1
runtime: php
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$

handlers:
- url: /css
  static_dir: public/css

- url: /fonts
  static_dir: public/fonts

- url: /img
  static_dir: public/img
  
- url: /js
  static_dir: public/js

- url: /*
  script: /public/index.php
  login: admin
  