application: vast-mapper-586
version: 1
runtime: php
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$

handlers:
- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /js
  static_dir: js

- url: /assets
  static_dir: assets
  
- url: /phpinfo.php
  script: phpinfo.php
  
- url: /.*
  script: index.php
  
- url: /profile/.*
  script: user_profile.php
  login: required
  
- url: /admin/.*
  script: admin.php
  login: admin
