<?php

define("PROJECT_NAME","<YOUR_PROJECT_NAME>");
define("PROJECT_ID","<YOUR_PROJECT_ID>");
define("CLIENT_ID","<YOUR_CLIENT_ID>");
define("CLIENT_SECRET","<YOUR_CLIENT_SECRET>");
define("REDIRECT_URI","<YOUR_REDIRECT_URI>");
